
/**
 * Tags/keywords for categorizing and describing venues, activities, and itineraries
 * These can be used for filtering, searching, and matching user preferences
 */
export const GO_OUT_TAGS = [
  "romantic",
  "cozy",
  "aesthetic",
  "serene",
  "peaceful",
  "chill",
  "lively",
  "vibrant",
  "energetic",
  "dreamy",
  "intimate",
  "luxurious",
  "classy",
  "casual",
  "fun",
  "playful",
  "nostalgic",
  "soulful",
  "calming",
  "magical",

  "seaside",
  "beachside",
  "waterfront",
  "rooftop",
  "open-air",
  "indoor",
  "outdoor",
  "garden",
  "nature",
  "greenery",
  "city-view",
  "skyline",
  "hill-view",
  "candle-lit",
  "sunset-view",

  "date-night",
  "valentine-special",
  "birthday",
  "anniversary",
  "farewell",
  "family-function",
  "friends-hangout",
  "couple-friendly",
  "group-party",
  "solo-friendly",
  "celebration",
  "casual-meet",
  "surprise-plan",

  "budget",
  "cheap",
  "affordable",
  "premium",
  "luxury",
  "value-for-money",
  "pocket-friendly",
  "splurge-worthy",

  "veg-friendly",
  "non-veg",
  "vegan",
  "alcohol-available",
  "no-alcohol",
  "fine-dining",
  "cafe",
  "street-food",
  "dessert-place",
  "brunch-spot",
  "late-night",

  "movie-night",
  "live-music",
  "DJ-night",
  "karaoke",
  "standup-comedy",
  "cultural",
  "art-inspired",
  "music-themed",

  "instagrammable",
  "pinterest-worthy",
  "aesthetic-photos",
  "reel-worthy",
  "influencer-popular",
  "underrated",
  "hidden-gem",
  "trending",
  "viral-spot",

  "family-friendly",
  "kid-friendly",
  "pet-friendly",
  "couple-only",
  "crowd-free",
  "peaceful-crowd",

  "good-ambience",
  "soft-music",
  "candle-light",
  "cozy-seating",
  "spacious",
  "quiet",
  "air-conditioned",

  "near-metro",
  "easy-parking",
  "centrally-located"
];
